name: Deploy to AWS S3

on:
  push:
    branches:
      - main
      - uat

env:
  MAIN_BUCKET_NAME: www.q247.app
  UAT_BUCKET_NAME: uat.q247.app
  AWS_REGION: eu-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: Build static site 
        run: npm run build
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            aws s3 sync out/ s3://${{ secrets.MAIN_BUCKET_NAME }} --delete --acl public-read
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            aws s3 sync out/ s3://${{ secrets.UAT_BUCKET_NAME }} --delete --acl public-read
          else
            echo "Not a deployable branch"
          fi
